/**
 * Compile CreditFile.sol with solc-js and emit both the artifact and the
 * TypeScript ABI the apps import. Regenerating the ABI here is the point:
 * it cannot drift from the bytecode we actually deploy.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const solc = require("solc");

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const repoRoot = join(pkgRoot, "..", "..");

const SOURCE_NAME = "CreditFile.sol";
const CONTRACT = "CreditFile";

const source = readFileSync(join(pkgRoot, "src", SOURCE_NAME), "utf8");

const input = {
  language: "Solidity",
  sources: { [SOURCE_NAME]: { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []) as { severity: string; formattedMessage: string }[];
const fatal = errors.filter((e) => e.severity === "error");
for (const e of errors) console.log(e.formattedMessage);
if (fatal.length > 0) {
  console.error(`[compile] FAILED with ${fatal.length} error(s)`);
  process.exit(1);
}

const artifact = output.contracts?.[SOURCE_NAME]?.[CONTRACT];
if (!artifact) {
  console.error(`[compile] No output for ${CONTRACT} in ${SOURCE_NAME}`);
  process.exit(1);
}

const abi = artifact.abi;
const bytecode = `0x${artifact.evm.bytecode.object}`;

const outDir = join(pkgRoot, "out");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, `${CONTRACT}.json`), JSON.stringify({ abi, bytecode }, null, 2));

const abiTs = `/**
 * Regenerated by \`pnpm contracts:build\` from CreditFile.sol. Do not hand-edit —
 * the compile script overwrites this file so the ABI can never drift from the
 * deployed bytecode.
 */
export const creditFileAbi = ${JSON.stringify(abi, null, 2)} as const;
`;
writeFileSync(join(repoRoot, "packages", "shared", "src", "creditFileAbi.ts"), abiTs);

console.log(`[compile] ${CONTRACT} ok — ${(bytecode.length - 2) / 2} bytes, ${abi.length} ABI entries`);
console.log(`[compile] wrote out/${CONTRACT}.json and packages/shared/src/creditFileAbi.ts`);
