/**
 * Regenerated by `pnpm contracts:build` from CreditFile.sol. Do not hand-edit —
 * the compile script overwrites this file so the ABI can never drift from the
 * deployed bytecode.
 */
export const creditFileAbi = [
  {
    type: "function",
    name: "recordReceipt",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payer", type: "address" },
      { name: "amountMicro", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordReceiptBatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payers", type: "address[]" },
      { name: "amountsMicro", type: "uint64[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "receiptCount",
    stateMutability: "view",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getReceipts",
    stateMutability: "view",
    inputs: [
      { name: "agent", type: "address" },
      { name: "sinceTs", type: "uint64" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "payer", type: "address" },
          { name: "amountMicro", type: "uint64" },
          { name: "timestamp", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getProfile",
    stateMutability: "view",
    inputs: [
      { name: "agent", type: "address" },
      { name: "windowSecs", type: "uint64" },
    ],
    outputs: [
      { name: "earnedInWindowMicro", type: "uint64" },
      { name: "distinctPayers", type: "uint32" },
      { name: "totalEarned", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "totalEarnedMicro",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "ReceiptRecorded",
    inputs: [
      { name: "agent", type: "address", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "amountMicro", type: "uint64", indexed: false },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
] as const;
